# Cache node modules - speeds up future builds
cache:
  paths:
    - node_modules
stages:
  - build
  - run
variables:
  S3_BUCKET_DEV: ${BUCKET_DEV}
.yarn_build:
  image: node:17.2.0
  script: |
    yarn # Install all dependencies
    yarn build:${APP_ENV} # Build command
  artifacts:
    paths:
      - ./build
      
yarn_dev:
  extends: .yarn_build
  stage: build
  before_script:
    - export APP_ENV="dev"
  only:
    refs:
      - develop
.deploy_aws:
  image: python:latest
  when: manual
  script: |
    pip install awscli
    aws s3 sync ./build/ s3://${S3_BUCKET}
deploy_dev:
  extends: .deploy_aws
  stage: run
  dependencies:
    - yarn_dev
  before_script:
    - export S3_BUCKET=${S3_BUCKET_DEV}
  only:
    refs:
      - develop